name: Java CI with Gradle

on:
  pull_request:
    branches-ignore:
      - ''
    types: [ opened, reopened ]
  push:
    branches-ignore:
      - ''
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.3.0
      - name: Set up JDK 1.17
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 1.17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.1.0
        with:
          name: Optifabric-Artifact
          path: build/libs/optifabric-*.*.jar
          if-no-files-found: error
